[build]
  command = "astro build"
  publish = "dist"

[functions]
  directory = ".netlify/v1/functions"

[dev]
  command = "npm run dev"
  port = 4321

[[headers]]
  for = "/*"

[headers.values]
  X-Frame-Options = "DENY"
  X-Content-Type-Options = "nosniff"
  Referrer-Policy = "no-referrer-when-downgrade"
  Permissions-Policy = "geolocation=(), microphone=(), camera=()"
  Content-Security-Policy = "default-src 'self' https://challenges.cloudflare.com"
